# Generated by Django 6.1.1 on 2026-09-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_modelo', models.CharField(max_length=150)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('anio', models.IntegerField()),
                ('precio_matriculado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
    ]
